# Generated by Django 6.0.2 on 2026-04-27 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_opportunity_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMatchmakingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('profile_snapshot_hash', models.CharField(blank=True, max_length=64)),
                ('opportunity_snapshot_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matchmaking_cache', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at', '-updated_at'],
            },
        ),
    ]
