# Generated by Django 6.0.2 on 2026-04-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=255)),
                ('source_mailbox', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('deadline', models.DateField()),
                ('agency', models.CharField(max_length=255)),
                ('sub_agency', models.CharField(blank=True, max_length=255)),
                ('naics_code', models.CharField(blank=True, max_length=50)),
                ('hyperlink', models.URLField(blank=True)),
                ('partner_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
