# Generated by Django 6.0.2 on 2026-04-07 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = []
