# Generated by Django 6.0.2 on 2026-04-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_remove_contract_notes_alter_contract_id_contractnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
