# Generated by Django 6.0.2 on 2026-04-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='NAICSCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('broad_category', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
