# Generated by Django 6.0.2 on 2026-04-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_naicscode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='source_mailbox',
        ),
        migrations.AlterField(
            model_name='contract',
            name='source',
            field=models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook'), ('procurement', 'Procurement')], db_index=True, max_length=20),
        ),
    ]
