# Generated by Django 6.0.2 on 2026-04-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_remove_contract_source_mailbox_alter_contract_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
