# Generated by Django 6.0.2 on 2026-04-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_alter_contract_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='procurement_portal',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contract',
            name='hyperlink',
            field=models.URLField(blank=True, db_index=True),
        ),
    ]
