# Generated by Django 6.0.2 on 2026-04-18 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_contract_procurement_portal_alter_contract_hyperlink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContractProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_progress', models.CharField(choices=[('NONE', 'None'), ('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost')], default='NONE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='contracts.contract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_progress_labels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'contract')},
            },
        ),
    ]
