# Generated by Django 6.0.2 on 2026-04-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_usercontractprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontractprogress',
            name='workflow_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('REVIEWING', 'Reviewing'), ('DRAFTING', 'Drafting'), ('SUBMITTED', 'Submitted')], default='NOT_STARTED', max_length=20),
        ),
    ]
