# Generated by Django 6.0.2 on 2026-04-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_usercontractprogress_workflow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontractprogress',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
