# Generated by Django 6.0.2 on 2026-04-25 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_mailboxconnection'),
        ('contracts', '0011_contractnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailIngestionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_message_id', models.CharField(max_length=255)),
                ('source_email', models.EmailField(blank=True, max_length=254)),
                ('sender', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('was_candidate', models.BooleanField(default=False)),
                ('filter_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_ingestion_messages', to='contracts.contract')),
                ('mailbox_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingested_messages', to='accounts.mailboxconnection')),
            ],
            options={
                'ordering': ('-received_at', '-created_at'),
                'unique_together': {('mailbox_connection', 'external_message_id')},
            },
        ),
    ]
