# Generated by Django 6.0.2 on 2026-04-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_dismissedcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontractprogress',
            name='pursuit_role',
            field=models.CharField(choices=[('UNDECIDED', 'Undecided'), ('PRIME', 'Prime'), ('SUB', 'Sub'), ('TEAM', 'Team')], default='UNDECIDED', max_length=20),
        ),
    ]
