# Generated by Django 6.0.2 on 2026-04-25 22:42

from django.db import migrations, models


def migrate_legacy_pursuit_roles(apps, schema_editor):
    UserContractProgress = apps.get_model('contracts', 'UserContractProgress')
    UserContractProgress.objects.filter(pursuit_role='SUB').update(pursuit_role='SUBCONTRACTING')
    UserContractProgress.objects.filter(pursuit_role='TEAM').update(pursuit_role='TEAMING')


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_usercontractprogress_pursuit_role'),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_pursuit_roles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='usercontractprogress',
            name='pursuit_role',
            field=models.CharField(choices=[('UNDECIDED', 'Undecided'), ('PRIME', 'Prime'), ('SUBCONTRACTING', 'Subcontracting'), ('TEAMING', 'Teaming'), ('PARTNERSHIP', 'Partnership')], default='UNDECIDED', max_length=20),
        ),
    ]
