# Generated by Django 6.0.2 on 2026-04-26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_emailingestionmessage'),
        ('contracts', '0014_alter_usercontractprogress_pursuit_role'),
    ]

    operations = [
    ]
