# Generated by Django 6.0.2 on 2026-03-12 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('label', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_email', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'email')},
            },
        ),
        migrations.CreateModel(
            name='CapabilityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('capability_summary', models.TextField(blank=True)),
                ('core_competencies', models.TextField(blank=True)),
                ('differentiators', models.TextField(blank=True)),
                ('naics_codes', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True)),
                ('past_performance', models.TextField(blank=True)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('source_pdf', models.FileField(blank=True, null=True, upload_to='capability_pdfs/')),
                ('ocr_extracted_text', models.TextField(blank=True)),
                ('is_ocr_generated', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capability_profiles', to='accounts.additionalemail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
