# Generated by Django 6.0.2 on 2026-03-14 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_additionalemail_capabilityprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capabilityprofile',
            name='is_ocr_generated',
        ),
        migrations.RemoveField(
            model_name='capabilityprofile',
            name='ocr_extracted_text',
        ),
    ]
