# Generated by Django 6.0.2 on 2026-03-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_capabilityprofile_is_ocr_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capabilityprofile',
            name='is_ocr_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='capabilityprofile',
            name='ocr_extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
