# Generated by Django 6.0.2 on 2026-03-14 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_capabilityprofile_is_ocr_generated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capabilityprofile',
            name='source_pdf',
        ),
    ]
