# Generated by Django 6.0.2 on 2026-03-14 06:55

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_capabilityprofile_source_pdf'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='additionalemail',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='additionalemail',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name='additionalemail',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('user'), name='unique_lower_email_per_user'),
        ),
    ]
