# Generated by Django 6.0.2 on 2026-03-14 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_capabilityprofile_source_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capabilityprofile',
            name='selected_email',
        ),
    ]
