# Generated by Django 6.0.2 on 2026-03-14 18:23

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_additionalemail_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='additionalemail',
            name='unique_lower_email_per_user',
        ),
        migrations.AddConstraint(
            model_name='additionalemail',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='unique_lower_email_globally'),
        ),
    ]
