# Generated by Django 6.0.2 on 2026-03-15 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_additionalemail_unique_lower_email_per_user_and_more'),
        ('accounts', '0007_user_reset_token_user_reset_token_expiration'),
    ]

    operations = [
    ]
