# Generated by Django 6.0.2 on 2026-04-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_20260315_1924'),
        ('contracts', '0008_usercontractprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capabilityprofile',
            name='is_ocr_generated',
        ),
        migrations.RemoveField(
            model_name='capabilityprofile',
            name='naics_codes',
        ),
        migrations.AddField(
            model_name='capabilityprofile',
            name='naics_codes',
            field=models.ManyToManyField(blank=True, related_name='capability_profiles', to='contracts.naicscode'),
        ),
    ]
