# Generated by Django 6.0.2 on 2026-04-25 08:18

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_capabilityprofile_is_ocr_generated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook')], max_length=20)),
                ('mailbox_email', models.EmailField(max_length=254)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('scope', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('needs_attention', 'Needs attention'), ('disconnected', 'Disconnected')], db_index=True, default='connected', max_length=30)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_cursor', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailbox_connections', to='accounts.additionalemail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(models.F('user'), models.F('provider'), django.db.models.functions.text.Lower('mailbox_email'), name='unique_mailbox_connection_per_user_provider_email')],
            },
        ),
    ]
