# Generated by Django 6.0.2 on 2026-04-25 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_connectedaccount'),
        ('contracts', '0012_dismissedcontract'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_message_id', models.CharField(max_length=255)),
                ('matched_terms', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_contracts', to='accounts.connectedaccount')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_matches', to='contracts.contract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('connected_account', 'provider_message_id')},
            },
        ),
    ]
