# Generated by Django 6.0.2 on 2026-04-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_mailboxconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='capabilityprofile',
            name='geographic_preferences',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='capabilityprofile',
            name='matchmaking_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='capabilityprofile',
            name='preferred_opportunity_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='capabilityprofile',
            name='services_offered',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='capabilityprofile',
            name='target_industries',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
