# Generated by Django 6.0.2 on 2026-04-26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_mailboxconnection'),
        ('accounts', '0011_mailboxcontract'),
    ]

    operations = [
    ]
